-- MySQL Script generated by MySQL Workbench
-- Wed Mar  6 11:54:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema runscape
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema runscape
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `runscape` DEFAULT CHARACTER SET utf8 ;
USE `runscape` ;

-- -----------------------------------------------------
-- Table `runscape`.`tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `runscape`.`tbl_user` (
  `id` VARCHAR(36) NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `email` VARCHAR(45) NULL,
  `phonenumber` VARCHAR(45) NULL,
  `disabled` TINYINT(1) NULL DEFAULT 0,
  `admin` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `runscape`.`tbl_activityType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `runscape`.`tbl_activityType` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(20) NULL,
  `removed` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `runscape`.`tbl_activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `runscape`.`tbl_activity` (
  `id` VARCHAR(36) NOT NULL,
  `fk_activity` VARCHAR(36) NOT NULL,
  `fk_user` VARCHAR(36) NOT NULL,
  `start_timestamp` TIMESTAMP NULL,
  `end_timestamp` TIMESTAMP NULL,
  `gpx` TEXT NULL,
  `removed` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_activity_tbl_user1_idx` (`fk_user` ASC),
  INDEX `fk_tbl_activity_tbl_actvityType1_idx` (`fk_activity` ASC),
  CONSTRAINT `fk_tbl_activity_tbl_user1`
    FOREIGN KEY (`fk_user`)
    REFERENCES `runscape`.`tbl_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_activity_tbl_actvityType1`
    FOREIGN KEY (`fk_activity`)
    REFERENCES `runscape`.`tbl_activityType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `runscape`.`tbl_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `runscape`.`tbl_position` (
  `id` VARCHAR(36) NOT NULL,
  `fk_activity` VARCHAR(36) NOT NULL,
  `latitude` DECIMAL(10,6) NULL,
  `longitude` DECIMAL(10,6) NULL,
  `altitude` SMALLINT UNSIGNED NULL,
  `removed` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_position_tbl_activity_idx` (`fk_activity` ASC),
  CONSTRAINT `fk_tbl_position_tbl_activity`
    FOREIGN KEY (`fk_activity`)
    REFERENCES `runscape`.`tbl_activity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `runscape`.`tbl_subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `runscape`.`tbl_subscription` (
  `id` VARCHAR(36) NOT NULL,
  `fk_user` VARCHAR(36) NOT NULL,
  `end_timestamp` TIMESTAMP NULL,
  `start_timestamp` TIMESTAMP NULL,
  `paused` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_subscription_tbl_user1_idx` (`fk_user` ASC),
  CONSTRAINT `fk_tbl_subscription_tbl_user1`
    FOREIGN KEY (`fk_user`)
    REFERENCES `runscape`.`tbl_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
